# Generated by Django 3.2 on 2021-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.TextField(default='Not have', max_length=1000),
        ),
    ]
