# Generated by Django 3.1.3 on 2021-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
