# Generated by Django 3.2 on 2021-04-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_song_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='FK_genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='FK_library',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.library'),
        ),
        migrations.AlterField(
            model_name='song',
            name='FK_moderator',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.moderator'),
        ),
        migrations.AlterField(
            model_name='song',
            name='FK_publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.publisher'),
        ),
    ]
