# Generated by Django 3.1.3 on 2021-04-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
