# Generated by Django 3.1.3 on 2021-04-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210412_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('FK_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.account')),
            ],
        ),
    ]
