# Generated by Django 3.2 on 2021-04-16 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_basket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_payment', models.CharField(max_length=200)),
                ('FK_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FK_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=5)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='post_code',
            new_name='zipcode',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='publisher_label',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='address',
            name='FK_account',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='FK_account',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='FK_account',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='FK_account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price_date',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='FK_account',
        ),
        migrations.RemoveField(
            model_name='song',
            name='FK_library',
        ),
        migrations.RemoveField(
            model_name='song',
            name='price',
        ),
        migrations.AddField(
            model_name='address',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basket',
            name='FK_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order'),
        ),
        migrations.AddField(
            model_name='basket',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventory',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderator',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basket',
            name='FK_song',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.song'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='FK_sale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sale'),
        ),
        migrations.AddField(
            model_name='order',
            name='FK_sale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.sale'),
        ),
    ]
