# Generated by Django 3.1.3 on 2021-04-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=8)),
                ('quantity', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
