# Generated by Django 3.2 on 2021-04-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210416_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='Unknown', max_length=300),
        ),
    ]
