# Generated by Django 3.1.3 on 2021-04-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_price', models.FloatField()),
                ('price_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('FK_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
            ],
        ),
    ]
