# Generated by Django 3.2 on 2021-04-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='FK_song_info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.songinfo'),
        ),
    ]
