# Generated by Django 3.2 on 2021-04-17 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_song_fk_song_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='FK_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='FK_sale',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='FK_sale',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='FK_order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.order'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='FK_song',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.song'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='FK_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
