# Generated by Django 3.1.3 on 2021-04-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=400)),
                ('FK_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.genre')),
                ('FK_library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.library')),
                ('FK_moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.moderator')),
                ('FK_publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publisher')),
            ],
        ),
    ]
