# Generated by Django 3.2 on 2021-04-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='DOR',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Publisher'), (2, 'Moderator'), (3, 'User')], default=3, null=True),
        ),
    ]
